config/routes.rb
Hotel::Application.routes.draw do
  resources :customers

  resources :stores

  resources :employees

  resources :reservations

  resources :admins

  get "home/index"

root :to => "home#index"

end

app/views/layouts/aboutus.html.erb
<center>
<h2>About Us</h2>
<p>
Aishwarya Grand is 3 star hotel and restuarant in kakinada with</br>
 all facilities and having resorts for functions and events all the </br>
decoration .......</br>
</p>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hotel</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<center>
<h1><font color="Black">HOTEL MANAGEMENT SYSTEM</font></h1>
<h3>Customer is king </h3>
</center>   
        <div id="main_container">
        <div id="menu">
        
        <ul>
        	<li><%= link_to "Admin", admins_path %></li>
            <li><%= link_to "Reservation", reservations_path %></li>
            <li><%= link_to "Employees", employees_path %></li>
            <li><%= link_to "Store", stores_path %></li>
            
        </ul>
        
        </div>
             
        <div id="columns">
        	<div class="column_top"></div>
            <div class="column_container">
            	
                
                <div id="left_column">
                	<h1>How to reach</h1>
                    <ul>  
                        <li><a href="http://maps.google.co.in/">Map route</a></li>
                        <li><a href="http://kakinada.ap.nic.in/">About Kakinada</a></li>
                        
                    </ul>
                    
                   <br />
<br />
 <h1>Services</h1>
                    <ul>
                        <li><%= link_to "customer online reservation", customers_path %></li>
                        <li><a href="http://larrywellsreview.com/holiday-party-decoration-storage-ideas/">Resorts Decoration</a></li>
                       
                    </ul>
           
             </div>
           
            
          <div id="right_column">
             <%= yield %>
              </div>
                
                
                
            </div>
            <div class="column_bottom"></h2></div>
        </div>
        
        
        
        
        </div>




</div>
</div>
          



</body>
</html>

app/views/layouts/contatus.html.erb
<center>
<h2>Contact us</h2>
<p>Aishwarya Grand Hotel 3 star hotel</p>
<p>Main Road III street</p>
<p>Opposite Multiplex</p>
<p>kakinada -03</p>
<p>East Godavari </p>
<p>contact numbers :0884-2222222</p>
<p>www.asihwaryagrand.com</p>
</center>